import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#2ae500",
        "surface-container-highest": "#26364a",
        "on-error": "#690005",
        "secondary-fixed-dim": "#bec6e0",
        "secondary": "#bec6e0",
        "outline-variant": "#3c4b35",
        "surface-container": "#102034",
        "surface-container-high": "#1b2b3f",
        "on-primary-fixed-variant": "#095300",
        "on-tertiary-container": "#bd1e26",
        "primary-fixed": "#79ff5b",
        "error": "#ffb4ab",
        "surface-bright": "#2a3a4f",
        "tertiary-fixed-dim": "#ffb3ad",
        "inverse-on-surface": "#213145",
        "inverse-surface": "#d3e4fe",
        "surface-variant": "#26364a",
        "on-tertiary-fixed": "#410004",
        "on-surface": "#d3e4fe",
        "on-background": "#d3e4fe",
        "secondary-fixed": "#dae2fd",
        "surface-dim": "#031427",
        "inverse-primary": "#106e00",
        "surface": "#031427",
        "surface-container-lowest": "#000f21",
        "tertiary-fixed": "#ffdad7",
        "secondary-container": "#3f465c",
        "background": "#031427",
        "on-tertiary-fixed-variant": "#930013",
        "on-primary-fixed": "#022100",
        "on-secondary": "#283044",
        "error-container": "#93000a",
        "on-primary": "#053900",
        "surface-tint": "#2ae500",
        "on-secondary-fixed": "#131b2e",
        "tertiary": "#fff8f7",
        "surface-container-low": "#0b1c30",
        "on-primary-container": "#107100",
        "on-tertiary": "#68000a",
        "on-secondary-container": "#adb4ce",
        "primary-container": "#39ff14",
        "tertiary-container": "#ffd3cf",
        "outline": "#85967c",
        "on-surface-variant": "#baccb0",
        "primary": "#efffe3",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#3f465c",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "unit-md": "16px",
        "unit-lg": "24px",
        "unit-xs": "4px",
        "mobile-width": "390px",
        "gutter": "24px",
        "unit-xl": "48px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "container-max": "1280px",
        "unit-sm": "8px",
      },
      fontFamily: {
        "mono-data": ["Space Grotesk", "monospace"],
        h2: ["Urbanist", "sans-serif"],
        "body-lg": ["Urbanist", "sans-serif"],
        h1: ["Urbanist", "sans-serif"],
        h3: ["Urbanist", "sans-serif"],
        "body-sm": ["Urbanist", "sans-serif"],
        "label-caps": ["Urbanist", "sans-serif"],
      },
      fontSize: {
        "mono-data": ["14px", { lineHeight: "1.4", fontWeight: "500" }],
        h2: ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        h1: ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        h3: ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "700" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};

export default config;
